// src/app/layout.tsx

import type { Metadata } from "next";
import { Providers } from "./providers";
import { M_PLUS_Rounded_1c, Roboto_Mono, } from "next/font/google";
import TypekitLoader from "../components/TypekitLoader"; //AdobeFontsの読み込みコンポーネント

const mPlusRounded1c = M_PLUS_Rounded_1c({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-m-plus-rounded-1c", 
});

const robotoMono = Roboto_Mono({
  weight: ["400"], 
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ja"
      className={`${mPlusRounded1c.variable} ${robotoMono.variable}`}
      suppressHydrationWarning={true}
    >
      <head>
      </head>
      <body>
        <Providers>{children}</Providers>
        <TypekitLoader />
      </body>
    </html>
  );
}
